// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crbtjexjjmmguzgtvrub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyYnRqZXhqam1tZ3V6Z3R2cnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTMyMzcsImV4cCI6MjA3MDM2OTIzN30.PFDFwsAoaSQXja6cW4kJ0KcBGzz4pJ2_0WgTNXaTK9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});